### ISSUE TITLE
Create marketing plan

### ISSUE THREAD

**Issue by marcoEDU** [marcoEDU/InLearnity#155]
- [x] define overall goals
- [x] define concrete goals + time limit
- [x] define ways to reach those goals
- [x] prioritize to do's
  - [ ] #159 create SEO Sitemap via Algolia Sitemap generator
  - [ ] #161 integrate Schema.org Markup in results / tech page to try optimize readability via Google
  - [ ] #162 create campaign schedule
  - [ ] #163 Auto update search queries database
  - [ ] #164 create blog posts to trending technologies
  - [ ] #165 Auto post about trending technologies
  - [ ] #166 create flyers & sticker
