### ISSUE TITLE
Big milestone: Switch from Webflow database to Algolia database only

### ISSUE THREAD

**Issue by marcoEDU** [marcoEDU/InLearnity#84]
- [x] recreate result page with algolia 
- [x] trigger animation when scrolling down
- [x] nested searches
- [x] search in both indexes
- [x] adapt import code => add missing details and simplify code, delete webflow part
- [x] integrate algolia on startpage to show what to build, content types and sources
- [x] replace "make" collection with single pages on "how to..."
- [x] fix missing pictures in "how to..." posts

- [x] remove sources and content categories from normal topics?
- [x] show description of sources & categories in search header if match

- [x] host website on server => github pages
- [x] replace picture URLs hosted on webflow / cloudfront with local images

- [x] fix scraper & reimport data to algolia

- [x] export & reimport search queries from algolia & replace "s/" with "search..."
